FROM node:12-alpine

ENV NODE_ENV=development API=

RUN apk add --update --no-cache tar unzip curl \
   && addgroup -g 1001 app \
   && adduser -s /sbin/nologin -u 1001 -G app -D app \
   && mkdir -p /usr/share/nginx/html \
   && chmod g+rwx -R /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

ADD ./package*.json ./
ADD ./ .
RUN yarn install && chown app:app /usr/share/nginx/html -R

VOLUME /usr/share/nginx/html/node_modules
# USER app

EXPOSE 3000

CMD yarn start