FROM node:12-alpine as build

ENV NODE_ENV=development API=

RUN apk add --update --no-cache tar unzip curl

WORKDIR /opt/app

COPY ./package*.json ./
RUN yarn install

VOLUME /opt/app/node_modules

COPY ./ .

CMD yarn build

FROM nginx:alpine

EXPOSE 3000

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /opt/app/build /usr/share/nginx/html

RUN chgrp -R 0 /usr/share/nginx && \
    chmod -R g=u /usr/share/nginx && \
    chgrp -R 0 /var/cache/nginx && \
    chmod -R g=u /var/cache/nginx && \
    chgrp -R 0 /var/run && \
    chmod -R g=u /var/run

CMD nginx -g "daemon off;"